export const exercises = [
  {
    id: "ex1",
    name: "Bench Press",
    description: "Compound chest exercise using a barbell",
    muscleGroups: ["Chest", "Triceps", "Shoulders"],
    defaultSets: 4,
    repRange: "8-12",
    lastWeight: 185,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex2",
    name: "Pull-ups",
    description: "Bodyweight back exercise",
    muscleGroups: ["Back", "Biceps", "Forearms"],
    defaultSets: 3,
    repRange: "8-12",
    lastWeight: 0, // bodyweight
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex3",
    name: "Squats",
    description: "Compound leg exercise using a barbell",
    muscleGroups: ["Quads", "Glutes", "Hamstrings"],
    defaultSets: 4,
    repRange: "8-12",
    lastWeight: 225,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex4",
    name: "Shoulder Press",
    description: "Compound shoulder exercise using dumbbells",
    muscleGroups: ["Shoulders", "Triceps"],
    defaultSets: 3,
    repRange: "8-12",
    lastWeight: 50,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex5",
    name: "Bicep Curls",
    description: "Isolation exercise for biceps using dumbbells",
    muscleGroups: ["Biceps", "Forearms"],
    defaultSets: 3,
    repRange: "10-15",
    lastWeight: 30,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex6",
    name: "Tricep Extensions",
    description: "Isolation exercise for triceps using a cable machine",
    muscleGroups: ["Triceps"],
    defaultSets: 3,
    repRange: "10-15",
    lastWeight: 40,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex7",
    name: "Deadlift",
    description: "Compound back exercise using a barbell",
    muscleGroups: ["Back", "Hamstrings", "Glutes", "Traps"],
    defaultSets: 3,
    repRange: "6-8",
    lastWeight: 275,
    image: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "ex8",
    name: "Leg Press",
    description: "Compound leg exercise using a machine",
    muscleGroups: ["Quads", "Glutes", "Hamstrings"],
    defaultSets: 3,
    repRange: "10-12",
    lastWeight: 360,
    image: "/placeholder.svg?height=100&width=100",
  },
]
